### ISSUE TITLE
Where does this addon create the DB files?

### ISSUE THREAD

**Issue by RMHogervorst** [tim-hellhake/influxdb-bridge#5]
The readme doesn't really tell me what this add-on really does. If I install this, I can save stuff in a time series db, but should I create that separately? Use a online version? Or does this add-on create and write to a local db?

**Comment by RMHogervorst** [comment]
And good morning

**Comment by RMHogervorst** [comment]
If somehow it could install a db on external usb drive for example that would save wearout on the sd card of my raspberry pi that runs the Mozilla gateway

**Comment by tim-hellhake** [comment]
> The readme doesn't really tell me what this add-on really does

Sorry, I'll add it to the description :sweat_smile:

> should I create that separately

You need to run an instance of InfluxDB somewhere.
The adapter only connects to the Instance and creates a [`DB`](https://docs.influxdata.com/influxdb/v1.8/query_language/manage-database/#) in the instance.

If you want to run InfluxDB on your PI, you have two choices:
* Install it directly 
* Install Docker and Docker Compose and run Grafana + InfluxDB using [this](https://github.com/tim-hellhake/influxdb-bridge/blob/master/docker-compose.yml) config. The config currently uses a Docker Volumes, which are typically located on the system partition, but that can be changed with two lines of config.

I'll usually prefer Docker because you don't need to deal with custom deb repos, and it's isolated from the system.
I'm happy to help you if you need more information.

**Comment by tim-hellhake** [comment]
I'm closing this issue for now.
If you have any questions feel free to ask :)

**Comment by Utopiah** [comment]
The setup worked well using docker-compose. I end up with Grafana running on http://raspberrypi:3000/ created a new user and logged in. It works, but I see no source. When I check the docker console I can see `influxdb_1` is correctly adding entries in real time when I interact with my Things via the Gateway. Is it something to setup or is it pre-filled and I missed something?

**Comment by tim-hellhake** [comment]
@Utopiah
I added a getting started with pictures.

**Comment by Utopiah** [comment]
Thanks a lot Tim. I dabbled with it and managed but I imagined others might also wonder if they are doing it right. Your quick guide is definitely helping!
